OLLAMA_BASE_URL = "http://152.70.248.22:1234"
DEEPSEEK_MODEL = "deepseek-r1:14b"
DB_TYPE = "sqlite"
DB_PATH = "data/scott.db"
OPENAI_API_KEY = "sk-1pUmQlsIkgla3CuvKTgCrzDZ3r0pBxO608YJvIHCN18lvOrn"
OPENAI_BASE_URL = "https://api.chatanywhere.tech/v1"
OPENAI_MODEL = "gpt-3.5-turbo" 